---
version: "3"
services:
  {{ cookiecutter.project_slug }}:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/{{ cookiecutter.project_slug }}/{{ cookiecutter.project_slug }}:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
    volumes:
      - /tmp:/app/log:z